### ISSUE TITLE
Pointshop won`t open

### ISSUE THREAD

**Issue by JgPfk** [Kamshak/Pointshop2#110]
Pointshop is not going to open, installation should be correct!

**Comment by Kamshak** [comment]
Do you have any errors / logs etc? Have you installed LibK and pac already?

**Comment by JgPfk** [comment]
The problem was the names of the files. I don't know which one of the 3 (pac3, libk or pointshop) i had to rename to get it working
btw. is there a way to get the addons?

**Comment by Kamshak** [comment]
You can find the extensions on Github as well: https://github.com/Kamshak?tab=repositories&q=ps2&type=&language=
