### ISSUE TITLE
CS:GO KNIVES SWEP

### ISSUE THREAD

**Issue by paldog** [Kamshak/Pointshop2#124]
Anyone Know how to add the CS:GO Knives addon to the pointshop? because this pointshop is different to pointshop 1 and i dont know how to install the knives :(

**Comment by Kamshak** [comment]
Install https://github.com/Kamshak/ps2-permaweaps and you should be able to just create them in the weapon creator

**Comment by paldog** [comment]
> Install https://github.com/Kamshak/ps2-permaweaps and you should be able to just create them in the weapon creator

Thank You Very Much :)
