### ISSUE TITLE
TEAM_SURVIVORS

### ISSUE THREAD

**Issue by VZR-Vityaz** [Kamshak/Pointshop2#129]
Hello. Please help, where and what should be entered so that only the Surviving team of players can take Airdrop

**Comment by VZR-Vityaz** [comment]
Zombie Survival

**Comment by Kamshak** [comment]
Hey, you can change the code in this file here: https://github.com/Kamshak/ps2_airdrops/blob/master/lua/entities/sent_airdropcrate/init.lua#L17

just change it to

```lua
  if caller:GetPos( ):Distance( self:GetPos( ) ) <= Pointshop2.Airdrops.MAX_USE_DISTANCE and caller:Team() == TEAM_SURVIVORS  then
```

**Comment by VZR-Vityaz** [comment]
thank!
