### ISSUE TITLE
Join rewards

### ISSUE THREAD

**Issue by Oyplap** [Kamshak/Pointshop2#130]
Hello,

I have the DiscordIntegration plugin and i was wondering what the code line is to give someone points for pointshop 2.

Right now it looks like this (see screenshot).
![Aantekening 2020-07-07 155119](https://user-images.githubusercontent.com/45702131/86791418-cbb5a680-c069-11ea-88bc-4fecbc9a918c.png)

what code do i need to type to give players points / donator points?

Kind regards,

Oyplap

**Comment by KennethSpeecke** [comment]
All the methods for giving points/items is located here: http://pointshop2.kamshak.com/en/latest/developer/points.html

**Comment by Oyplap** [comment]
> All the methods for giving points/items are located here: http://pointshop2.kamshak.com/en/latest/developer/points.html
> 
> What your looking for is this piece of code.
> `ply:PS2_AddStandardPoints()`
> 
> Be sure to look at the documentation he provided for extra params in the methods.

I really have no idea of how to code. Could you help me write the code?

**Comment by KennethSpeecke** [comment]
Change the code from line 419 to ling 421 to.
`
RewardFunc = function(ply)
    if ply.PS2_Wallet then
    ply:PS2_AddStandardPoints(500)
    end
end,
`

I wrote this on my phone since im not home. If this does not work then leave another comment and me or someone else wil take another look at it.

**Comment by Oyplap** [comment]
it works thank you!

**Comment by KennethSpeecke** [comment]
You're welcome.

This issue can be closed i guess.
