### ISSUE TITLE
pointshop2_drops

### ISSUE THREAD

**Issue by Vitjaz1409** [Kamshak/Pointshop2#131]
Hello. I have one single problem: drops works, and the item issues correctly, but the opening animation is broken and closes with an error: 

[pointshop2_drops] addons/pointshop2_drops/lua/ps2/modules/dlc/cl_dcrateopenframe.lua:148: attempt to call method 'GetConfiguredIconControl' (a nil value)
  1. s - addons/pointshop2_drops/lua/ps2/modules/dlc/cl_dcrateopenframe.lua:148
   2. succ - addons/pointshop2_libk/lua/libk/shared/1_sh_promises.lua:57
    3. Done - addons/pointshop2_libk/lua/libk/shared/1_sh_promises.lua:125
     4. Then - addons/pointshop2_libk/lua/libk/shared/1_sh_promises.lua:116
      5. Map - addons/pointshop2_libk/lua/libk/shared/1_sh_promises.lua:337
       6. LoadIcons - addons/pointshop2_drops/lua/ps2/modules/dlc/cl_dcrateopenframe.lua:143
        7. UnpackCrate - addons/pointshop2_drops/lua/ps2/modules/dlc/cl_dcrateopenframe.lua:173
         8. func - addons/pointshop2_drops/lua/ps2/modules/dlc/sh_drops.lua:158
          9. unknown - lua/includes/extensions/net.lua:32

**Comment by Vitjaz1409** [comment]
Please help with this error

**Comment by Kamshak** [comment]
Do you have any custom (coded) items? What's in your crates?

**Comment by Vitjaz1409** [comment]
Points

**Comment by Vitjaz1409** [comment]
In drop only the Points

**Comment by timothybvf** [comment]
the drop crates don't open at all, no gui or anything when you hit E on them, just a console error.

**Comment by Vitjaz1409** [comment]
The box opens and gives the element, but there is no animation, this opening animation does not work, and closes with the error I wrote

**Comment by Kamshak** [comment]
Try reuploading your pointshop2 addon, it's a fairly weird error, no idea how that could happen

**Comment by Vitjaz1409** [comment]
Okay I will try
