### ISSUE TITLE
Pointshop 2 Equipment Error

### ISSUE THREAD

**Issue by Marco15453** [Kamshak/Pointshop2#132]
I always getting errors when trying to Equip the same item twice

Example:
Equipping Player Models -> Unequip it -> Equipit again won't even work

**Comment by Marco15453** [comment]
I fixed it myself!

**Comment by Kamshak** [comment]
Ver nice! What turned out to be the issue?

**Comment by Marco15453** [comment]
there is a function in Line 252 in SH_util.lua in LibK, i just comment that out and now it's working fine
