### ISSUE TITLE
Ghost mode shows some accessories, trials and hats

### ISSUE THREAD

**Issue by Oyplap** [Kamshak/Pointshop2#139]
Is there a fix on how to disable accessories, trials and hats from showing while someone is in ghostmode?

The developer of gmod-deathrun-ghost found a fix for pointshop1 here: https://github.com/ceifa/gmod-deathrun-ghost/issues/3
But i need a fix for PointShop2.

Kind regards,
Oyplap

**Comment by victornishtyakov** [comment]
You can replace function ITEM:OnEquip( )
lua\kinv\items\pointshop\sh_base_hat.lua

```
function ITEM:OnEquip( )
	if SERVER then
		return
	end

	local ply = self:GetOwner()
	if not IsValid( ply ) then
		timer.Simple( 1, function()
			if IsValid( self:GetOwner( ) ) then
				self:OnEquip( )
			end
		end )
		return
	end

	if not ply:Alive( ) then
		return
	end

    if GhostMode and ply:IsGhost() then
        return
    end

	if ply.IsSpec and ply:IsSpec() then
		return
	end

	if ply.IsGhost and ply:IsGhost() then
		return
	end

	self:AttachOutfit( )
end
```

**Comment by Oyplap** [comment]
Works, thank you!
