### ISSUE TITLE
Pointshop is refusing to open, no idea why.

### ISSUE THREAD

**Issue by BlooberryPi3** [Kamshak/Pointshop2#143]
I've renamed folders, reinstalled the files into my addon folder multiple times for my server, it refuses to open with f3. what am I doing wrong?

**Comment by Oyplap** [comment]
Have you installed these:

https://github.com/Kamshak/Pointshop2#requirements

**Comment by BlooberryPi3** [comment]
https://i.imgur.com/FgaOjo0.png

These are all the addons I have in the server's addons folder. I should have them all.

**Comment by Oyplap** [comment]
You are obviously missing PAC 3

Like i asked: have you installed these:
https://github.com/Kamshak/Pointshop2#requirements

**Comment by Oyplap** [comment]
Did pointshop2 ever worked for you?

Or have you tried reinstalling pointshop2?

Kind regards,
Oyplap

**Comment by BlooberryPi3** [comment]
I have pac3 right there? Libk and then pac3

My server recently had a big issue happen and I've had to fully remake my server, pointshop 2 has yet to work, but it worked in the past.

**Comment by Kamshak** [comment]
@BlooberryPi3 please try renaming all folders to lowercase (e.g. libk instead of LibK), uppercase folder names can cause issues on linux

**Comment by Oyplap** [comment]
you can also delete sv.db file (in servername\garrysmod)

But create a backup, because some important stuff is in that file. 

You can also edit the sv.db file with a mysql reader iirc

**Comment by BlooberryPi3** [comment]
> 
> 
> @BlooberryPi3 please try renaming all folders to lowercase (e.g. libk instead of LibK), uppercase folder names can cause issues on linux

This was it! making them all lowercase made it all work. Thank you!
