### ISSUE TITLE
Can't re-equip item / preview doesn't update

### ISSUE THREAD

**Issue by Reigners** [Kamshak/Pointshop2#145]
Whenever I remove a player model or accessory/hat, I cannot equip it again. Equipment slot just shows red instead of yellow. At the same time the preview doesn't update. Unequipped model still shows in the preview (not on actual player model). 
Even worse with accessory items or hats. They show ontop of each other in the preview screen and on the player model.
If I quip a hat and unequip it back to inventory, it still shows on the preview. If I put on a different hat, it shows with the previous one. More hats you equip, more are mushed together.

I also tried using "Pointshop2-2.24.1" from releases section and it doesn't have that issue, and runs fine.
But "Pointshop2-2.24.1" lags the server whenever anyone equips / unequips an item.

Found that both issues are caused in "lua/ps2/server/sv_pointshopcontroller_shop.lua" by functions "Pointshop2Controller:unequipItem" and "Pointshop2Controller:equipItem".

Comparing Poinshop2-master and Pointshop2-2.24.1 both functions are completely different from each other and I really don't know what to do.

Note that I'm running a clean server install. Only addons are Libk, Pac3, Pointshop2, Ulib, Ulx.

If anyone could give some ideas would be amazing.

**Comment by Kamshak** [comment]
Do you get any errors in console when that happens?

**Comment by Reigners** [comment]
> 
> 
> Do you get any errors in console when that happens?

No I don't. 
Only stuff I see is
In game console
`controllerAction:	send 	equipItem
controllerAction:	send 	unequipItem
`
In server console
`OnHolster:	on holster	Player [1][Rei]`

**Comment by Reigners** [comment]
Fixed the issue by reverting Dimantio's changes in commit [Fix nil item and unequip issue](https://github.com/Kamshak/Pointshop2/commit/9448d40518b1eb224bcb6eb97441ff7124815937#diff-dc436b329f4da6c88b0b6ce79d829ac4fc33746b454604e2bcbad25a8e2985fe)
Now it works fine and as it should.
I can equip/unequip items and preview updates as well.

**Comment by Dimantio** [comment]
Change "resolved" to "done" from what I remember this should fix this issue.

**Comment by Reigners** [comment]
> 
> 
> Change "resolved" to "done" from what I remember this should fix this issue.

Yes is did fix the issues. Thank you.
