### ISSUE TITLE
Error when try to reequip same model (items)

### ISSUE THREAD

**Issue by Marco15453** [Kamshak/Pointshop2#163]
Since new vrsin of pointshop  i cannot longer equip the same item twice.

Error:

[ERROR] Player Marco15453 tried to unequipItem empty slot Model

**Comment by Marco15453** [comment]
Full error since opening of shop


Marco15453: !shop
Marco15453@Pointshop2View -> Pointshop2Controller:adminGetServers(  ) | Transaction 1 len 69, Compressed: false
Marco15453@Pointshop2View -> Pointshop2Controller:unequipItem( Model ) len 68
[ERROR] Player Marco15453 tried to unequipItem empty slot Model

**Comment by askrealcookie** [comment]
I don't know if I can help with that but come to discord https://discord.gg/N9DmwwX and describe your problem on #support channel.

**Comment by Marco15453** [comment]
Closing because Fixed
