### ISSUE TITLE
No bodygroup section in model creation

### ISSUE THREAD

**Issue by TolyaArzamas** [Kamshak/Pointshop2#166]
Hello, can you please help me with my issue? The bodygroup section in model creation doesn't appear for me. It appeared one time but since then I can't find it anywhere. How can I fix this?

Also, is there any way to make models not in pointshop but with notepad? 
![20210628233744_1](https://user-images.githubusercontent.com/86627598/123694996-14620300-d86b-11eb-9553-f64c74f58c48.jpg)
![20210628234614_1](https://user-images.githubusercontent.com/86627598/123695000-15933000-d86b-11eb-9bae-55e42a33c5b0.jpg)

**Comment by Kamshak** [comment]
Hi, there's a weird display issue with the tabs there, there's a solution/trick to this here: https://discord.com/channels/332587378290196482/332587418760904704/835416574860460032

You cannot create items in notepad but you can create them in lua if you want, see here: https://gist.github.com/Kamshak/e343784e15966b1fa8a38544793293e9

**Comment by TolyaArzamas** [comment]
Thank you so much for both fix and blog!
