### ISSUE TITLE
Problem with PH:X integration

### ISSUE THREAD

**Issue by miniwinz78** [Kamshak/Pointshop2#177]
hi,

have this error with the PropHunt:X

[pointshop2] addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:88: attempt to index local 'attacker' (a nil value)
  1. fn - addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:88
   2. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
    3. unknown - gamemodes/prop_hunt/entities/entities/ph_prop.lua:127

and the props is not removed.

**Comment by Vinzuerio** [comment]
It should be fixed in PH:X on upcoming june update, there was missing `inflictor` argument where PS2 needs it, my bad.

**Comment by askrealcookie** [comment]
Great, thanks for informing us! We've been wondering for a long time why PS2 was throwing an error here. Good to know that it will be fixed soon!
