### ISSUE TITLE
Particle effects issue after pac3 update

### ISSUE THREAD

**Issue by pkmnmstr98** [Kamshak/Pointshop2#186]
I understand this might be a pac3 issue but the effect is included in the default for the GMAN pet (larvae_glow_b)

Attempting to create unknown particle system 'default' 
Attempting to create unknown particle system 'larvae_glow_b'

this error is client side

**Comment by pkmnmstr98** [comment]
Also can anyone point me to where the color for the inventory boxes are set :)?

**Comment by askrealcookie** [comment]
sooo I'm not sure, but maybe try changing that:
ps2/lua/kinv/client/cl_ditemslot.lua @ line ~71
If it doesn't work you may need to use custom skin(https://github.com/snowywolf/Pointshop-2-Skin) or search in different place maybe.

**Comment by pkmnmstr98** [comment]
I found out where to change it !!! Changing stuff in ps2/lua/kinv/client/cl_ditemslot.lua will change the color for all of the boxes but not for individual items

**Comment by pkmnmstr98** [comment]
> sooo I'm not sure, but maybe try changing that: ps2/lua/kinv/client/cl_ditemslot.lua @ line ~71 If it doesn't work you may need to use custom skin(https://github.com/snowywolf/Pointshop-2-Skin) or search in different place maybe.

Also, the pac3 version you linked. Is that the latest version you're aware of that works perfectly with pointshop2? I heard pac3 had/has some vulnerabilities that's why i had updated the one i was using.

**Comment by askrealcookie** [comment]
> I found out where to change it !!! Changing stuff in ps2/lua/kinv/client/cl_ditemslot.lua will change the color for all of the boxes but not for individual items
Great to hear you found the solution.

Not sure about pac3. There might be newer version working but I don't really know. I think the only issue with pac is when generating icons. If you want to use custom icons you could probably just install latest (but you'd need to create and upload all your icons to the server, it might take a lot of time depending on amount of items in shop).

**Comment by askrealcookie** [comment]
that's unfortunate haha. Could you elaborate on your question? What do you mean by "not in the shop", in "Not for sale" category? Client renders icon only once and then caches it. I think only icons in categories that are open or can be seen by players (not sure about that) are generated.

**Comment by pkmnmstr98** [comment]
Ahh okay you answered my question then.  Thank you for the help!

**Comment by pkmnmstr98** [comment]
So i uploaded the pac version you sent and I'm still getting particle errors. It starts as soon as i buy the default per GMAN which comes with the particles attached.

Attempting to create unknown particle system 'larvae_glow_b'  (x4)

**Comment by pkmnmstr98** [comment]
> I can't really help you with your first problem as you should use older version of pac3 anyways to ensure icons are generated correctly(for some reasons newer versions can't do that) like this one: https://github.com/CapsAdmin/pac3/tree/0a5ac3501782ed848411ada341e4e9d3fdf281d1
> 
> About color of inventory boxes I'm not really sure if I understood you correctly but you should probably look into ps2/lua/kinv/client/cl_ditemstack.lua

Also in the model viewer the option to add a particle effect doesn't show up
