### ISSUE TITLE
Inventory start

### ISSUE THREAD

**Issue by pkmnmstr98** [Kamshak/Pointshop2#187]
Anyone know where the code is located for when a new player joins and their inventory ID is created ? Using MySQL and the table is called inventories

**Comment by Kamshak** [comment]
That would be here: https://github.com/Kamshak/Pointshop2/blob/master/lua/ps2/server/sv_pointshopcontroller.lua#L67
what are you looking to do?

**Comment by pkmnmstr98** [comment]
> That would be here: https://github.com/Kamshak/Pointshop2/blob/master/lua/ps2/server/sv_pointshopcontroller.lua#L67 what are you looking to do?

Wanted to add a start up inventory for new players. So when a new player join they have some basic guns or basic things in their inventory

**Comment by pkmnmstr98** [comment]
@Kamshak Also, if i add another property to an already existing item persistence will it brake the table/delete it ?

**Comment by Kamshak** [comment]
It should be fine as long as you manually add the column in your database as well
