### ISSUE TITLE
PurchaseData

### ISSUE THREAD

**Issue by pkmnmstr98** [Kamshak/Pointshop2#188]
Trying to add more variables to the purchasedata in MYSQL. Im trying to add a way to identify a specific item inside the inventory. For example i could have 2 ak47s and they have the same persistenceID but nothing to set them apart other than maybe purchasedata time of creation. Is there a function i can use to modify the purchase data variable and then update only MySQL. Also does pointshop2 update persistence data every map change? Or only whenever an item is changed inside shop

**Comment by Kamshak** [comment]
It's updated instantly whenever something is changed inside the shop. What do you want to store in the purchasedata? In MySQL the purchasedata is just a JSON blob so you can put whatever you want in there. E.g.

```

KInventory.Item.findById( itemId ) :Then( function( item )
  item.purchaseData.myExtraData = "test"
  return item:save()
end )

```

**Comment by pkmnmstr98** [comment]
I wanted to add a LVL/EXP value to it. Also wanted to find someway to identify that item in specific in an inventory

**Comment by pkmnmstr98** [comment]
@Kamshak is there a way to update only that data client side?? Also, if i have the item equipped and then i move it back into inventory it removes the change i made to the item.

**Comment by pkmnmstr98** [comment]
Here's the code im using

`    local Gitem = ply:PS2_GetItemInSlot("Hat")

    KInventory.Item.findById(Gitem.id):Then(function(item)
        item.purchaseData.effect = WEffect

        return item:save()
    end)`

**Comment by pkmnmstr98** [comment]
Doing this will keep it from changing if the player moves the item around.
KInventory.ITEMS[Gitem.id] = item

Still need to find a way to update it :/

**Comment by Kamshak** [comment]
If you're updating the item that is in an Inventory or slot it's important that you modify the item instance that PS2 uses, there is a global lookup table `KInventory.ITEMS` that you can use. If you need that data clientside after you'd need to manually network the change, you can use ITEM:ClientRPC for that, e.g.:

*sh_purchase_data_update_mixin.lua*
```lua
-- Extend base_item for purchase data updates
local PurchaseDataUpdateMixin = {}
function PurchaseDataUpdateMixin:included( klass )
    klass.static.AllowRPC("PurchaseDataUpdated")
end

if CLIENT then
  function PurchaseDataUpdateMixin:PurchaseDataUpdated(newData)
    self.purchaseData = newData
  end
end

if SERVER then
  function PurchaseDataUpdateMixin:UpdatePurchaseData(newData)
    self.purchaseData = newData
    return self:save( ):Then(function( )
      self:ClientRPC("PurchaseDataUpdated", newData)
    end)
  end
end

KInventory.RegisterItemClassMixin("base_pointshop_item", PurchaseDataUpdateMixin)
```

E.g.
```lua
local itemId = 12345

-- Get the item like this if you have the id but don't know if it's equipped or in inventory
local item = KInventory.ITEMS[12345]
-- if this is null you can use the db (KInventory.Item.findById)
-- you can also get the item from a slot or elsewhere, e.g.
-- local item = ply:PS2_GetItemInSlot("Hat")

local newPurchaseData = table.Copy(item.purchaseData)
newPurchaseData.effect = "test effect"
item:UpdatePurchaseData(newPurchaseData)
```

**Comment by pkmnmstr98** [comment]
Awesome!!! Thank you for all the help!! @Kamshak

**Comment by pkmnmstr98** [comment]
It works perfectly!
